name: SessionSkip
main: re.dbn.david191212.plugins.bungee.SessionSkip
version: 1.7
author: David191212
#Original author: NickG365
#Original website: http://gameon365.net
#Original email: nick@gameon365.net